### ISSUE TITLE
Not working on iOS 11

### ISSUE THREAD

**Issue by whoot** [nowsecure/fsmon#38]
Hey,

i downloaded and installed the 'fsmon_1.4_iphoneos-arm.deb' to my iPhone with iOS 11.1.2.
However, no matter what I try, I always get the same error:
```
root# fsmon -h
Killed: 9
```

Is there any way to get this tool working on iOS 11 or any replacement for it?

**Comment by trufae** [comment]
Thats probably because a missing required entitlement for the latest jb. Just resign in it should be enough. I’ll update the bin and do a new release later this week when i get some spare time

Thanks for reporting

**Comment by whoot** [comment]
Wow, that was fast. However, it does still not work :/
```
root# chmod +x fsmon-ios 
root# ./fsmon-ios 
dyld: Library not loaded: /System/Library/Frameworks/CoreServices.framework/CoreServices
  Referenced from: //./fsmon-ios
  Reason: image not found
Abort trap: 6
```

**Comment by trufae** [comment]
I can confirm this error. Seems like Apple added this CoreServices framework as a new dependency for iOS12.

https://www.theiphonewiki.com/wiki//System/Library/Frameworks

I'm downloading the old iOS11 SDK and doing a new build with it, that should be enough to make it work

**Comment by trufae** [comment]
Ok, so i found an issue in the Apple linker that is not inheriting the -weak_frameworks flag to the dependencies of the weakedly linked frameworks.

Setting a minos option doesnt solves the problem because the ios12 XCode SDK is linking against the CoreServices framework which is only available in  iOS12. Switching to older SDKs is kind of a pain, so the best solution i found was to binary patch with r2 the 64 bit slice of the compiled binary:

```
$ OFF=`rabin2 -H fsmon-ios.arm_64.1 |grep -C 2 /CoreSer|head -n1|cut -d ' ' -f 1` r2 -qnwc "wx 18000080 @ $OFF" fsmon-ios.arm64
```

And here's the result:

[fsmon-ios.arm_64.1.zip](https://github.com/nowsecure/fsmon/files/2768158/fsmon-ios.arm_64.1.zip)

**Comment by whoot** [comment]
Works as intended. Thanks for the quick fix!

**Comment by lisongzhe** [comment]
ios 12 not work also killed 9

**Comment by dengshuaige** [comment]
so?
 

 




------------------ 原始邮件 ------------------
发件人: "李松哲"<notifications@github.com>;
发送时间: 2019年5月13日(星期一) 下午3:59
收件人: "nowsecure/fsmon"<fsmon@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [nowsecure/fsmon] Not working on iOS 11 (#38)




ios 12 not work also killed 9
